[theme]
primaryColor = "#F63366"
backgroundColor = "#d7c092"
secondaryBackgroundColor = "#aaa241"
textColor = "#614625"
font = "sans serif"
headingFont  = "'Love Ya Like A Sister':https://fonts.googleapis.com/css2?family=Love+Ya+Like+A+Sister&display=swap"
